flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/asayers/snappy-framed.git
    commit: 6c2c865
  extra-dep: true

extra-deps:
- attoparsec-binary-0.2
- binary-0.8.2.1
- directory-1.2.6.3
- snappy-0.2.0.2
resolver: lts-6.3
